name: SAFE Network Apps
description: A directory of the most popular SAFE Network apps
url: 'https://apps.safenetwork.org'
baseurl: ''
github: 'https://github.com/safenetwork/apps.safenetwork.org'
permalink: /:title/
markdown: kramdown
cdn: ''
gems:
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
